const MAGNETOMETER_AVG_SAMPLE = 18;
const ANGLE_THRESHOLD = 10.0;
const PEAK_IN_RANGE_THRESHOLD = 2.5;

const PEAK_SHOW_MODE = {
  list: 'List',
  graph: 'Graph'
}

export { MAGNETOMETER_AVG_SAMPLE, ANGLE_THRESHOLD, PEAK_IN_RANGE_THRESHOLD, PEAK_SHOW_MODE };